#### Import Libraries

In [1]:
from pathlib import Path
import pandas as pd

#### Processed Paths

In [2]:
processed_folder = Path("../data/processed")

matches_path = processed_folder / "matches.csv"
deliveries_path = processed_folder / "deliveries.csv"
players_path = processed_folder / "players.csv"

#### Load Datasets

In [3]:
matches_df = pd.read_csv(matches_path,parse_dates=["match_date"])
deliveries_df = pd.read_csv(deliveries_path,parse_dates=["match_date"])
players_df = pd.read_csv(players_path)

C:\Users\abhil\AppData\Local\Temp\ipykernel_3864\3240825528.py:2: DtypeWarning: Columns (0: season) have mixed types. Specify dtype option on import or set low_memory=False.
  deliveries_df = pd.read_csv(deliveries_path,parse_dates=["match_date"])

#### Display Shape

In [4]:
print("Matches shape:", matches_df.shape)
print("Deliveries shape:", deliveries_df.shape)
print("Players shape:", players_df.shape)

Matches shape: (1243, 25)
Deliveries shape: (295732, 34)
Players shape: (27909, 6)

#### Sample Data

In [7]:
print(f"Matches Data:\n{matches_df.head()}")
print(f"Deliveries Data:\n{deliveries_df.head()}")
print(f"Players Data:\n{players_df.head()}")

Matches Data:
   match_id season match_date       city  \
0   1082591   2017 2017-04-05  Hyderabad
1   1082592   2017 2017-04-06       Pune
2   1082593   2017 2017-04-07     Rajkot
3   1082594   2017 2017-04-08     Indore
4   1082595   2017 2017-04-08  Bengaluru

                                       venue match_type gender team_type  \
0  Rajiv Gandhi International Stadium, Uppal        T20   male      club
1    Maharashtra Cricket Association Stadium        T20   male      club
2     Saurashtra Cricket Association Stadium        T20   male      club
3                     Holkar Cricket Stadium        T20   male      club
4                      M.Chinnaswamy Stadium        T20   male      club

                        team_1                       team_2  ... result  \
0          Sunrisers Hyderabad  Royal Challengers Bangalore  ...    NaN
1       Rising Pune Supergiant               Mumbai Indians  ...    NaN
2                Gujarat Lions        Kolkata Knight Riders  ...    NaN
3              Kings XI Punjab       Rising Pune Supergiant  ...    NaN
4  Royal Challengers Bangalore             Delhi Daredevils  ...    NaN

  method eliminator  player_of_match             event_name  \
0    NaN        NaN     Yuvraj Singh  Indian Premier League
1    NaN        NaN        SPD Smith  Indian Premier League
2    NaN        NaN          CA Lynn  Indian Premier League
3    NaN        NaN       GJ Maxwell  Indian Premier League
4    NaN        NaN        KM Jadhav  Indian Premier League

  event_match_number event_group overs balls_per_over   source_file
0                1.0         NaN    20              6  1082591.json
1                2.0         NaN    20              6  1082592.json
2                3.0         NaN    20              6  1082593.json
3                4.0         NaN    20              6  1082594.json
4                5.0         NaN    20              6  1082595.json

[5 rows x 25 columns]
Deliveries Data:
   match_id season match_date  innings         batting_team  \
0   1082591   2017 2017-04-05        1  Sunrisers Hyderabad
1   1082591   2017 2017-04-05        1  Sunrisers Hyderabad
2   1082591   2017 2017-04-05        1  Sunrisers Hyderabad
3   1082591   2017 2017-04-05        1  Sunrisers Hyderabad
4   1082591   2017 2017-04-05        1  Sunrisers Hyderabad

                  bowling_team  target_runs  target_overs  over  \
0  Royal Challengers Bangalore          NaN           NaN     0
1  Royal Challengers Bangalore          NaN           NaN     0
2  Royal Challengers Bangalore          NaN           NaN     0
3  Royal Challengers Bangalore          NaN           NaN     0
4  Royal Challengers Bangalore          NaN           NaN     0

   delivery_number  ...  is_four is_six is_boundary is_wicket  \
0                1  ...        0      0           0         0
1                2  ...        0      0           0         0
2                3  ...        1      0           1         0
3                4  ...        0      0           0         0
4                5  ...        0      0           0         0

   is_bowler_wicket  wickets_on_delivery  player_dismissed  dismissal_kind  \
0                 0                    0               NaN             NaN
1                 0                    0               NaN             NaN
2                 0                    0               NaN             NaN
3                 0                    0               NaN             NaN
4                 0                    0               NaN             NaN

   fielder   source_file
0      NaN  1082591.json
1      NaN  1082591.json
2      NaN  1082591.json
3      NaN  1082591.json
4      NaN  1082591.json

[5 rows x 34 columns]
Players Data:
   match_id season                         team    player_name  \
0   1082591   2017  Royal Challengers Bangalore       CH Gayle
1   1082591   2017  Royal Challengers Bangalore  Mandeep Singh
2   1082591   2017  Royal Challengers Bangalore        TM Head
3   1082591   2017  Royal Challengers Bangalore      KM Jadhav
4   1082591   2017  Royal Challengers Bangalore      SR Watson

  player_registry_id   source_file
0           db584dad  1082591.json
1           c3a96caf  1082591.json
2           12b610c2  1082591.json
3           99d63244  1082591.json
4           4329fbb5  1082591.json

#### Missing Data

In [8]:
matches_df.isnull().sum().sort_values(
    ascending=False
)

event_group           1243
eliminator            1227
method                1220
result                1218
event_match_number      74
city                    51
winner                  25
player_of_match          9
match_id                 0
team_1                   0
team_type                0
gender                   0
match_type               0
venue                    0
match_date               0
season                   0
team_2                   0
win_by_runs              0
win_by_wickets           0
toss_winner              0
toss_decision            0
event_name               0
overs                    0
balls_per_over           0
source_file              0
dtype: int64

In [9]:
deliveries_df.isnull().sum().sort_values(
    ascending=False
).head(15)

fielder             285011
player_dismissed    281027
dismissal_kind      281027
target_overs        153429
target_runs         153429
match_id                 0
season                   0
bowling_team             0
match_date               0
innings                  0
ball                     0
batter                   0
non_striker              0
bowler                   0
batter_runs              0
dtype: int64

In [10]:
players_df.isnull().sum()

match_id              0
season                0
team                  0
player_name           0
player_registry_id    0
source_file           0
dtype: int64

#### Check Match IDs

In [11]:
print(
    "Unique matches in matches dataset:",
    matches_df["match_id"].nunique()
)

print(
    "Unique matches in deliveries dataset:",
    deliveries_df["match_id"].nunique()
)

print(
    "Unique matches in players dataset:",
    players_df["match_id"].nunique()
)

Unique matches in matches dataset: 1243
Unique matches in deliveries dataset: 1243
Unique matches in players dataset: 1243

#### Check Duplicates

In [12]:
print(
    "Duplicate match IDs:",
    matches_df["match_id"].duplicated().sum()
)

Duplicate match IDs: 0

In [13]:
print(
    "Duplicate player participation records:",
    players_df.duplicated(
        subset=[
            "match_id",
            "team",
            "player_name",
        ]
    ).sum()
)

Duplicate player participation records: 0

In [14]:
deliveries_df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
295727    False
295728    False
295729    False
295730    False
295731    False
Length: 295732, dtype: bool

#### Validate Scores

In [15]:
deliveries_df[
    [
        "batter_runs",
        "extra_runs",
        "total_runs",
    ]
].describe()

         batter_runs     extra_runs     total_runs
count  295732.000000  295732.000000  295732.000000
mean        1.290117       0.068336       1.358453
std         1.664418       0.342939       1.650191
min         0.000000       0.000000       0.000000
25%         0.000000       0.000000       0.000000
50%         1.000000       0.000000       1.000000
75%         1.000000       0.000000       1.000000
max         6.000000       7.000000       7.000000

In [16]:
invalid_run_rows = deliveries_df[
    deliveries_df["total_runs"]
    != (
        deliveries_df["batter_runs"]
        + deliveries_df["extra_runs"]
    )
]

print(
    "Invalid run rows:",
    len(invalid_run_rows)
)

Invalid run rows: 0

#### Validate Teams

In [17]:
matches_df[
    [
        "team_1",
        "team_2",
        "winner",
    ]
].head(10)

,team_1,team_2,winner
0,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad
1,Rising Pune Supergiant,Mumbai Indians,Rising Pune Supergiant
2,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders
3,Kings XI Punjab,Rising Pune Supergiant,Kings XI Punjab
4,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore
5,Sunrisers Hyderabad,Gujarat Lions,Sunrisers Hyderabad
6,Mumbai Indians,Kolkata Knight Riders,Mumbai Indians
7,Kings XI Punjab,Royal Challengers Bangalore,Kings XI Punjab
8,Rising Pune Supergiant,Delhi Daredevils,Delhi Daredevils
9,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians

#### Display Seasons

In [18]:
matches_df["season"].value_counts().sort_index()

season
2007/08    58
2009       57
2009/10    60
2011       73
2012       74
2013       76
2014       60
2015       59
2016       60
2017       59
2018       60
2019       60
2020/21    60
2021       60
2022       74
2023       74
2024       71
2025       74
2026       74
Name: count, dtype: int64

#### Basic Dataset Summary

In [19]:
summary = {
    "total_matches": matches_df["match_id"].nunique(),
    "total_deliveries": len(deliveries_df),
    "total_player_records": len(players_df),
    "unique_players": players_df["player_name"].nunique(),
    "unique_teams": players_df["team"].nunique(),
    "first_match_date": matches_df["match_date"].min(),
    "latest_match_date": matches_df["match_date"].max(),
}

summary

{'total_matches': 1243,
 'total_deliveries': 295732,
 'total_player_records': 27909,
 'unique_players': 811,
 'unique_teams': 19,
 'first_match_date': Timestamp('2008-04-18 00:00:00'),
 'latest_match_date': Timestamp('2026-05-31 00:00:00')}