# <b>House Price Prediction</b>

## <b>Phase 5 – Feature Engineering</b>

### <b>Objective</b>

The goal of this notebook is to prepare the cleaned dataset for machine learning by converting categorical variables into numerical representations.

Tasks covered:

- Load cleaned dataset
- Separate features and target
- Identify categorical and numerical features
- Encode categorical variables
- Verify transformed dataset
- Save engineered dataset

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../data/processed/Housing_Cleaned.csv')

In [3]:
df_fe = df.copy()

In [4]:
print("Dataset Shape:", df_fe.shape)

df_fe.head()

Dataset Shape: (545, 13)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [5]:
X = df_fe.drop("price", axis=1)

y = df_fe["price"]

In [7]:
numerical_columns = X.select_dtypes(
    include=["int64", "float64"]
).columns

categorical_columns = X.select_dtypes(
    include="str"
).columns

print("Numerical Columns:")
print(numerical_columns)

print("\nCategorical Columns:")
print(categorical_columns)

Numerical Columns:
Index(['area', 'bedrooms', 'bathrooms', 'stories', 'parking'], dtype='str')

Categorical Columns:
Index(['mainroad', 'guestroom', 'basement', 'hotwaterheating',
       'airconditioning', 'prefarea', 'furnishingstatus'],
      dtype='str')

In [8]:
binary_columns = [
    "mainroad",
    "guestroom",
    "basement",
    "hotwaterheating",
    "airconditioning",
    "prefarea"
]

for column in binary_columns:
    df_fe[column] = df_fe[column].map({
        "yes": 1,
        "no": 0
    })

In [9]:
df_fe = pd.get_dummies(
    df_fe,
    columns=["furnishingstatus"],
    drop_first=True,
    dtype=int
)

In [10]:
df_fe.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,0,0
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,0,0
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,1,0
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,0,0
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,0,0

In [11]:
df_fe.info()

<class 'pandas.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 14 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   price                            545 non-null    int64
 1   area                             545 non-null    int64
 2   bedrooms                         545 non-null    int64
 3   bathrooms                        545 non-null    int64
 4   stories                          545 non-null    int64
 5   mainroad                         545 non-null    int64
 6   guestroom                        545 non-null    int64
 7   basement                         545 non-null    int64
 8   hotwaterheating                  545 non-null    int64
 9   airconditioning                  545 non-null    int64
 10  parking                          545 non-null    int64
 11  prefarea                         545 non-null    int64
 12  furnishingstatus_semi-furnished  545 non-null    int64
 13  furnishingstatus_unfurnished     545 non-null    int64
dtypes: int64(14)
memory usage: 59.7 KB

In [12]:
print(df_fe.isnull().sum())

price                              0
area                               0
bedrooms                           0
bathrooms                          0
stories                            0
mainroad                           0
guestroom                          0
basement                           0
hotwaterheating                    0
airconditioning                    0
parking                            0
prefarea                           0
furnishingstatus_semi-furnished    0
furnishingstatus_unfurnished       0
dtype: int64

In [13]:
df_fe.to_csv(
    "../data/processed/Housing_Feature_Engineered.csv",
    index=False
)

#### <b>Feature Engineering Summary</b>

##### Binary Features

The following binary categorical variables were encoded:

- mainroad
- guestroom
- basement
- hotwaterheating
- airconditioning
- prefarea

Encoding:

- yes → 1
- no → 0

##### Multi-Class Feature

The `furnishingstatus` column was transformed using one-hot encoding.

##### <b>Outcome</b>

The dataset now contains only numerical features, making it suitable for machine learning algorithms.