# <b>House Price Prediction</b>

## <b>Phase 6 – Data Preprocessing</b>

### <b>Objective</b>

The goal of this notebook is to prepare the dataset for machine learning.

Tasks covered:

- Load feature-engineered dataset
- Split features and target
- Train-test split
- Feature scaling
- Save preprocessing pipeline
- Save processed datasets

In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
import joblib

In [3]:
df = pd.read_csv("../data/processed/Housing_Feature_Engineered.csv")

In [4]:
print(df.shape)

df.head()

(545, 14)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,0,0
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,0,0
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,1,0
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,0,0
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,0,0

In [5]:
X = df.drop("price", axis=1)

y = df["price"]

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [7]:
print("Training Features :", X_train.shape)
print("Testing Features  :", X_test.shape)

print("Training Target   :", y_train.shape)
print("Testing Target    :", y_test.shape)

Training Features : (436, 13)
Testing Features  : (109, 13)
Training Target   : (436,)
Testing Target    : (109,)

In [8]:
numerical_columns = X_train.select_dtypes(
    include=["int64", "float64"]
).columns

print(numerical_columns)

Index(['area', 'bedrooms', 'bathrooms', 'stories', 'mainroad', 'guestroom',
       'basement', 'hotwaterheating', 'airconditioning', 'parking', 'prefarea',
       'furnishingstatus_semi-furnished', 'furnishingstatus_unfurnished'],
      dtype='str')

In [9]:
preprocessing_pipeline = Pipeline(
    steps=[
        ("scaler", StandardScaler())
    ]
)

In [10]:
X_train_scaled = preprocessing_pipeline.fit_transform(X_train)

In [11]:
X_test_scaled = preprocessing_pipeline.transform(X_test)

In [12]:
X_train_scaled = pd.DataFrame(
    X_train_scaled,
    columns=X_train.columns,
    index=X_train.index
)

X_test_scaled = pd.DataFrame(
    X_test_scaled,
    columns=X_test.columns,
    index=X_test.index
)

In [13]:
X_train_scaled.head()

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
46,0.384168,0.055271,1.539173,2.587644,0.407155,-0.466773,-0.746420,-0.230521,1.501243,0.367957,-0.552620,-0.870669,-0.676900
93,0.929181,0.055271,1.539173,-0.912499,0.407155,-0.466773,1.339728,-0.230521,1.501243,2.709987,-0.552620,1.148542,-0.676900
335,-0.607755,-1.283514,-0.557950,-0.912499,0.407155,-0.466773,1.339728,-0.230521,1.501243,1.538972,-0.552620,-0.870669,-0.676900
412,-1.155492,0.055271,-0.557950,0.254215,0.407155,-0.466773,1.339728,-0.230521,-0.666115,-0.803059,1.809561,-0.870669,1.477322
471,-0.637730,0.055271,-0.557950,0.254215,0.407155,-0.466773,-0.746420,-0.230521,-0.666115,-0.803059,-0.552620,-0.870669,1.477322

In [14]:
joblib.dump(
    preprocessing_pipeline,
    "../models/preprocessing_pipeline.pkl"
)

['../models/preprocessing_pipeline.pkl']

In [15]:
X_train_scaled.to_csv(
    "../data/processed/X_train.csv",
    index=False
)

X_test_scaled.to_csv(
    "../data/processed/X_test.csv",
    index=False
)

y_train.to_csv(
    "../data/processed/y_train.csv",
    index=False
)

y_test.to_csv(
    "../data/processed/y_test.csv",
    index=False
)

#### <b>Data Preprocessing Summary</b>

##### Train-Test Split

- Training Data: 80%
- Testing Data: 20%

##### Feature Scaling

- StandardScaler applied.
- Scaler fitted only on training data.
- Test data transformed using the fitted scaler.

##### Pipeline

A preprocessing pipeline was created and saved for reuse during model training and deployment.