## Sample Data Understanding

In [ ]:
import pandas as pd
import sys
from pathlib import Path

In [ ]:
# Add project root to path
project_root = Path.cwd().parent

if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

In [2]:
from src.data.load_data import (
    load_sample_train_data
)

In [3]:
df = load_sample_train_data(
    n_rows=5000
)

df.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [4]:
df.shape

(5000, 23)

In [5]:
df.columns.tolist()

['Unnamed: 0',
 'trans_date_trans_time',
 'cc_num',
 'merchant',
 'category',
 'amt',
 'first',
 'last',
 'gender',
 'street',
 'city',
 'state',
 'zip',
 'lat',
 'long',
 'city_pop',
 'job',
 'dob',
 'trans_num',
 'unix_time',
 'merch_lat',
 'merch_long',
 'is_fraud']

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             5000 non-null   int64
 1   trans_date_trans_time  5000 non-null   str
 2   cc_num                 5000 non-null   int64
 3   merchant               5000 non-null   str
 4   category               5000 non-null   str
 5   amt                    5000 non-null   float64
 6   first                  5000 non-null   str
 7   last                   5000 non-null   str
 8   gender                 5000 non-null   str
 9   street                 5000 non-null   str
 10  city                   5000 non-null   str
 11  state                  5000 non-null   str
 12  zip                    5000 non-null   int64
 13  lat                    5000 non-null   float64
 14  long                   5000 non-null   float64
 15  city_pop               5000 non-null   int64
 16  job                    5000 non-null   str
 17  dob                    5000 non-null   str
 18  trans_num              5000 non-null   str
 19  unix_time              5000 non-null   int64
 20  merch_lat              5000 non-null   float64
 21  merch_long             5000 non-null   float64
 22  is_fraud               5000 non-null   int64
dtypes: float64(5), int64(6), str(12)
memory usage: 1.6 MB

In [7]:
memory_usage = (
    df.memory_usage(deep=True)
      .sum()
      / 1024**2
)

print(
    f"Memory Usage: {memory_usage:.2f} MB"
)

Memory Usage: 1.64 MB

In [8]:
missing_values = (
    df.isnull()
      .sum()
      .sort_values(
          ascending=False
      )
)

missing_values[
    missing_values > 0
]

Series([], dtype: int64)

In [9]:
duplicate_count = (
    df.duplicated()
      .sum()
)

print(
    f"Duplicate Rows: {duplicate_count}"
)

Duplicate Rows: 0

In [10]:
df["is_fraud"].value_counts()

is_fraud
0    4978
1      22
Name: count, dtype: int64

In [12]:
summary = pd.DataFrame({
    "Column": df.columns,
    "DataType": df.dtypes.values,
    "Missing Values": df.isnull().sum().values,
    "Unique Values": [
        df[col].nunique()
        for col in df.columns
    ]
})

summary

                   Column DataType  Missing Values  Unique Values
0              Unnamed: 0    int64               0           5000
1   trans_date_trans_time      str               0           4936
2                  cc_num    int64               0            876
3                merchant      str               0            692
4                category      str               0             14
5                     amt  float64               0           3906
6                   first      str               0            327
7                    last      str               0            452
8                  gender      str               0              2
9                  street      str               0            876
10                   city      str               0            811
11                  state      str               0             50
12                    zip    int64               0            866
13                    lat  float64               0            864
14                   long  float64               0            865
15               city_pop    int64               0            799
16                    job      str               0            465
17                    dob      str               0            863
18              trans_num      str               0           5000
19              unix_time    int64               0           4936
20              merch_lat  float64               0           4999
21             merch_long  float64               0           5000
22               is_fraud    int64               0              2

### <b>Feature Classification</b>

#### <b>Customer Features</b>
- cc_num
- gender
- dob
- job
- city_pop

#### <b>Transaction Features</b>
- trans_date_trans_time
- merchant
- category
- amt

#### <b>Location Features</b>
- city
- state
- lat
- long
- merch_lat
- merch_long

#### <b>Target Variable</b>
- is_fraud

## Full Data Understanding

In [13]:
from src.data.load_data import load_full_train_data

df_full = load_full_train_data()

In [14]:
df_full.shape

(1296675, 23)

In [15]:
df_full.isnull().sum().sum()

np.int64(0)

In [18]:
(df_full["is_fraud"].value_counts(normalize=True) *100).round(3)

is_fraud
0    99.421
1     0.579
Name: proportion, dtype: float64

In [17]:
print(df_full.duplicated().sum())

0